# Task 2

**Given the following matrices:**

            A = [2. -1,  3         B = [1,  2     
                 0,  4,  1],           -2,  0     
                                        5, -3]    

1.  Identify the number of rows and columns in each matrix
2.  Determine whether the matrices can be multiplied. If so, specify whether it's `(AB)`, `(BA)`, or both.
3.  If the multiplication is defined, compute the resulting matrix

### Solution

1.  The number of rows and columns in `Matrix A` is `2` by `3` respectively and the number of rows and columns in `Matrix B` is `3` by `2` respectively.

2.  The matrices can be multiplied since the number of columns in `Matrix A` is the same as the number of rows in `Matrix B`. So both `(AB)` and `(BA)` will work.

3.  Resulting matrix

In [1]:
import numpy as np

In [2]:
A = np.array([[2, -1, 3],
              [0, 4, 1]])

B = np.array([[1, 2],
              [-2, 0],
              [5, -3]])

In [3]:
matrix1 = np.dot(A, B)
matrix2 = np.dot(B, A)
print("Matrix A:\n", A, "\nMatrix B:\n", B)
print("\nMatrix '(AB)' is:\n", matrix1)
print("Matrix '(BA)' is:\n", matrix2)

Matrix A:
 [[ 2 -1  3]
 [ 0  4  1]] 
Matrix B:
 [[ 1  2]
 [-2  0]
 [ 5 -3]]

Matrix '(AB)' is:
 [[19 -5]
 [-3 -3]]
Matrix '(BA)' is:
 [[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
