# Part 1

In [2]:
import numpy as np

In [5]:
#3.1 representing data as matrix

scores = np.array([[80, 70, 90],
                  [60, 85, 75],
                  [95, 88, 92],
                  [70, 60, 65]])

print("Initial Scores:\n", scores)

Initial Scores:
 [[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]


In [6]:
#3.2 total scores per students

sum_rows = np.sum(scores, axis=1)           # sum of all rows

for i, total in enumerate(sum_rows, 1):                 # sum of each rows
    print(f"Total score for Student{i} is {total}")

Total score for Student1 is 240
Total score for Student2 is 220
Total score for Student3 is 275
Total score for Student4 is 195


In [15]:
#3.3 applying weights

weighed_maths = np.array([2, 1, 1])     # array for maths x 2

weighted_maths = scores * weighed_maths     # multiplying math * 2 array with scores
print("Since maths is twice as important, weighted maths is:\n", weighted_maths)

new_score = weighted_maths             # updating scores

sum_rows2 = np.sum(weighted_maths, axis=1)      # sum of all rows in the new array

for i, total in enumerate(sum_rows2, 1):                # sum of each rows of students
    print(f"Total score for Student{i} is {total}")


Since maths is twice as important, weighted maths is:
 [[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]
Total score for Student1 is 320
Total score for Student2 is 280
Total score for Student3 is 370
Total score for Student4 is 265


In [16]:
#3.4 average score per subject
subjects = ["Maths", "English", "Science"]              # array for subject
sub_avg = np.mean(new_score, axis=0)               # calculating the mean/average for all scores/columns

for subject, avg in zip(subjects, sub_avg):     # average of each subject/column
    print(f"Average of {subject} is {avg}")

Average of Maths is 152.5
Average of English is 75.75
Average of Science is 80.5


In [18]:
#3.5 final grades using matrix multiplication
grades = np.array([0.5, 0.3, 0.2])              # grades
final_grade = np.matmul(scores, grades)

for i, grade in enumerate(final_grade, 1):
    print(f"Final Grade for Student{i} is {grade:.2f}")


Final Grade for Student1 is 79.00
Final Grade for Student2 is 70.50
Final Grade for Student3 is 92.30
Final Grade for Student4 is 66.00


In [ ]:
#3.6 comparing students (vector subtraction)
student1 = scores[0]
student2 = scores[1]

sum_student1 = np.sum(scores[0])
sum_student2 = np.sum(scores[1])

comparing_student = sum_student1 - sum_student2 

print("Overall Comparison:")
if comparing_student > 0:
    print("Student1 performed better")
elif comparing_student < 0:
    print("Student2 performed better")
else:
    print("Both student tie")

Student1 performed better


# Hands-On

In [7]:
#.1 Representing data as matrix

scores_2 = np.array([[80, 70, 90, 80], 
                     [60, 85, 75, 75], 
                     [95, 88, 92, 72], 
                     [70, 60, 65, 75], 
                     [65, 75, 80, 80]])

print("Initial Scores:\n", scores_2)

Initial Scores:
 [[80 70 90 80]
 [60 85 75 75]
 [95 88 92 72]
 [70 60 65 75]
 [65 75 80 80]]


In [8]:
#.2 total scores per students

total_scores = np.sum(scores_2, axis=1)

for i, total in enumerate(total_scores, 1):
        print(f"Total score for Student{i} is {total}")


Total score for Student1 is 320
Total score for Student2 is 295
Total score for Student3 is 347
Total score for Student4 is 270
Total score for Student5 is 300


In [11]:
#.3 Scalar multiplication
weighh = np.array([1, 1, 3, 1])  
weighed_scores = scores_2 * weighh

weighted_total_scores = np.sum(weighed_scores, axis=1)
print("Since Science is thrice as important, weighted science is:\n", weighed_scores)


for i, total in enumerate(weighted_total_scores, 1):
    print(f"Total score for Student{i} is {total}")

Since Science is thrice as important, weighted science is:
 [[ 80  70 270  80]
 [ 60  85 225  75]
 [ 95  88 276  72]
 [ 70  60 195  75]
 [ 65  75 240  80]]
Total score for Student1 is 500
Total score for Student2 is 445
Total score for Student3 is 531
Total score for Student4 is 400
Total score for Student5 is 460


In [12]:
#.4 Final grades

weigh = np.array([0.4, 0.3, 0.2, 0.1])
final_grade = np.matmul(scores_2, weigh)

for i, grades in enumerate(final_grade, 1):
    print(f"Student {i}: {grades:.2f}")


Student 1: 79.00
Student 2: 72.00
Student 3: 90.00
Student 4: 66.50
Student 5: 72.50


In [13]:
#.5 Comparing grades
student_1 = scores_2[0]
student_2 = scores_2[1]

sum_student_1 = np.sum(scores_2[0])
sum_student_2 = np.sum(scores_2[1])

comparing_students = sum_student_1 - sum_student_2

print("Overall Comparison:")
if comparing_students > 0:
    print("Student1 performed better")
elif comparing_students < 0:
    print("Student2 performed better")
else:
    print("Both student tie")

Overall Comparison:
Student1 performed better
