In [2]:
import numpy as np

In [65]:
#3.1 representing data as matrix

scores = np.array([[80, 70, 90],
                  [60, 85, 75],
                  [95, 88, 92],
                  [70, 60, 65]])

In [68]:
#3.2 total scores per students

sum_rows = np.sum(scores, axis=1)           # sum of all rows

for i, total in enumerate(sum_rows, 1):                 # sum of each rows
    print(f"Total score for Student{i} is {total}")

Total score for Student1 is 320
Total score for Student2 is 280
Total score for Student3 is 370
Total score for Student4 is 265


In [ ]:
#3.3 applying weights

weighed_maths = np.array([2, 1, 1])     # array for maths x 2

weighted_maths = scores * weighed_maths     # multiplying math * 2 array with scores
print("Since maths is twice as important, weighted maths is:\n", weighted_maths)

scores = weighted_maths             # updating scores

sum_rows2 = np.sum(weighted_maths, axis=1)      # sum of all rows in the new array

for i, total in enumerate(sum_rows2, 1):                # sum of each rows of students
    print(f"Total score for Student{i} is {total}")


Since maths is twice as important, weighted maths is:
 [[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]
Total score for Student1 is 320
Total score for Student2 is 280
Total score for Student3 is 370
Total score for Student4 is 265


In [ ]:
#3.4 average score per subject
subjects = ["Maths", "English", "Science"]              # array for subject
sub_avg = np.mean(scores, axis=0)               # calculating the mean/average for all scores/columns

for subject, avg in zip(subjects, sub_avg):     # average of each subject/column
    print(f"Average of {subject} is {avg}")

Average of Maths is 152.5
Average of English is 75.75
Average of Science is 80.5


In [ ]:
#3.5 final grades using matrix multiplication
grades = np.array([0.5, 0.3, 0.2])              # grades
final_grade = np.matmul(scores, grades)

for i, grade in enumerate(final_grade, 1):
    print(f"Final Grade for Student{i} is {grade}")


Final Grade for Student1 is 119.0
Final Grade for Student2 is 100.5
Final Grade for Student3 is 139.8
Final Grade for Student4 is 101.0


In [62]:
#3.6 comparing students (vector subtraction)
student1 = scores[0]
student2 = scores[1]

sum_student1 = np.sum(scores[0])
sum_student2 = np.sum(scores[1])

comparing_student = sum_student1 - sum_student2 

if comparing_student > 0:
    print("Student1 performed better")
elif comparing_student < 0:
    print("Student2 performed better")
else:
    print("Both student tie")

Student1 performed better
