In [1]:
import numpy as np

In [2]:
A = [[2, -1], [0, 3]]
B = [[1, 4], [-2, 5]]
c = 2
d = 3


compute_A = np.array([[2, -1], [0, 3]])
compute_B = np.array([[1, 4], [-2, 5]])
print(f"This is matrix A:\n", compute_A)
print(" ")
print(f"This is matrix B:\n", compute_B)

This is matrix A:
 [[ 2 -1]
 [ 0  3]]
 
This is matrix B:
 [[ 1  4]
 [-2  5]]


a.  Compute the following: `(cA)`, `(dB)`, and `(c + d)A`.

In [3]:
cA = c * compute_A
dB = d * compute_B
cdA = (c +d) * compute_A

print("cA:\n",cA)
print(" ")
print("dB:\n",dB)
print(" ")
print("(c + d)A:\n",cdA)

cA:
 [[ 4 -2]
 [ 0  6]]
 
dB:
 [[ 3 12]
 [-6 15]]
 
(c + d)A:
 [[10 -5]
 [ 0 15]]


b. Using results gotten, verify the scalar multiplication properties

In [4]:
scalar_mult = cA + (d * compute_A)
print("The scalar multiplication is:\n",scalar_mult)

The scalar multiplication is:
 [[10 -5]
 [ 0 15]]


c. Transpose of `A` and `B`

In [5]:
a_transpose = compute_A.T
b_transpose = compute_B.T

print("The transpose of A is:\n", a_transpose)
print("")
print("The transpose of B is:\n", b_transpose)

The transpose of A is:
 [[ 2  0]
 [-1  3]]

The transpose of B is:
 [[ 1 -2]
 [ 4  5]]


d. Check if `(A)` and `(B)` are invertible by computing their determinants. If they are invertible, find:  and

In [7]:
# finding determinants of  A and B arrays
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)


print("The determinant of Array A is: \n", det_A)

print("The determinant of Array B : \n", det_B)


The determinant of Array A is: 
 6.0
The determinant of Array B : 
 13.0


**Since the determinant of both A & B > 0, then it is invertible**

In [11]:
# so the inverse of A and B arrays
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)


print(f"The Inverse of Array A is: \n {A_inv}\n")
print(f"The Inverse of Array B is: \n {B_inv}")

The Inverse of Array A is: 
 [[0.5        0.16666667]
 [0.         0.33333333]]

The Inverse of Array B is: 
 [[ 0.38461538 -0.30769231]
 [ 0.15384615  0.07692308]]
