#### Question 1
Create a 6x6 NumPy array with random integers between 1 and 50. Display the array.

In [31]:
import numpy as np

arr = np.random.randint(1, 50, size=(6, 6))
print(arr)
# print(arr.ndim)

[[15 41 45 21 35 20]
 [38  2 42 14 32 33]
 [ 1 31 20 31 15 14]
 [43 10 33  1 47 46]
 [ 5 25 15 14 24 42]
 [41  3 39 19 45 10]]


#### Question 2
Extract the following from the array you created in Question1: The first two rows. The last three columns. All even numbers in the array

In [38]:
first2row = arr[:2]
print("First two rows are: \n",first2row,"\n")

last3col = arr[:, -3:]
print("last 3 columns are:\n", last3col,"\n")

# to print all the even numbers in array
even_numbers = arr[arr % 2 == 0]
print("Even numbers in array are:\n", even_numbers)


First two rows are: 
 [[15 41 45 21 35 20]
 [38  2 42 14 32 33]] 

last 3 columns are:
 [[21 35 20]
 [14 32 33]
 [31 15 14]
 [ 1 47 46]
 [14 24 42]
 [19 45 10]] 

Even numbers in array are:
 [20 38  2 42 14 32 20 14 10 46 14 24 42 10]


#### Question 3
Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D

In [46]:
# reshaping to 3D (3, 2, 6)
reshaped = arr.reshape(3, 2, 6)
print("Reshaped array into 3D:\n", reshaped, "\n")

# flatten back to 1D
print("Flattend array back:\n", reshaped.flatten())

Reshaped array into 3D:
 [[[15 41 45 21 35 20]
  [38  2 42 14 32 33]]

 [[ 1 31 20 31 15 14]
  [43 10 33  1 47 46]]

 [[ 5 25 15 14 24 42]
  [41  3 39 19 45 10]]] 

Flattend array back:
 [15 41 45 21 35 20 38  2 42 14 32 33  1 31 20 31 15 14 43 10 33  1 47 46
  5 25 15 14 24 42 41  3 39 19 45 10]


#### Question 4
Generate a 4x4 identify matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.

In [89]:
# 4x4 identity matrix
matrix4x4 = np.identity(4)          # or use eye
print("4x4 Identity matrix:\n", matrix4x4)

# replacing the diagonal with numbers 10-40 with 10 step
diag_matrix = np.diag(np.arange(10, 50, 10))            # np.fill_diagonal(four_by_four, range(10, 50, 10))
print("Replacing the diagonal:\n", diag_matrix)

4x4 Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Replacing the diagonal:
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


#### Question 5
Perform matrix multiplication between: A 3x4 matrix of random integers (1-10), A 4x3 matrix of random integers (1-10)

In [83]:
matrix1 = np.random.randint(1, 10, size=(3, 4))
matrix2 = np.random.randint(1, 10, size=(4, 3))

print("Matrix 1 (3x4):\n", matrix1)
print("Matrix 2 (4x3):\n", matrix2)

mult = np.matmul(matrix1, matrix2)
print("\nMatrix 1 multipled by Matrix 2 is:\n",mult)

Matrix 1 (3x4):
 [[9 2 8 6]
 [2 1 1 2]
 [4 3 9 5]]
Matrix 2 (4x3):
 [[3 6 6]
 [2 7 5]
 [5 2 6]
 [5 6 5]]

Matrix 1 multipled by Matrix 2 is:
 [[101 120 142]
 [ 23  33  33]
 [ 88  93 118]]


#### Question 6
Create a function takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1.+

In [ ]:
def array_operation():
    try:
        x = int(input('Enter number of rows here: '))
        y = int(input('Enter number of columns here: '))
        arr = []
        for i in range(x):
            for j in range(y):
                arr.append(int(input(f'Value at row {i} and column {j}')))
        array = np.array(arr).reshape(x, y)
        print('Original array:')
        print(array)

        square_array = np.where(array % 2 == 0, array ** 2, array)
        odd_square_array = np.where(square_array % 2 != 0, -1, square_array)
        return odd_square_array
    except ValueError as e:
        return(e)
    except Exception as e:
        return e

array_operation()